export enum BillingCycle {
  ONCE = 'ONCE',
  DAILY = 'DAILY',
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  ANNUALLY = 'ANNUALLY',
  SEMIANNUALLY = 'SEMIANNUALLY',
  BIENNIALLY = 'BIENNIALLY',
  TRIENNIALLY = 'TRIENNIALLY',
}